name: hello_world
description: "Crockery Manager Pro - Professional Barcode Inventory System."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- UI Icons & Fonts ---
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0

  # --- NEW: BARCODE SCANNER ---
  mobile_scanner: ^5.2.3
  
  # --- Offline Database (Fast Storage) ---
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # --- Storage Path ---
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0
  
  # --- Code Generators (Database) ---
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png